/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngebotPersonalTrainingRouteImport } from './routes/angebot.personal-training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngebotPersonalTrainingRoute = AngebotPersonalTrainingRouteImport.update({
  id: '/angebot/personal-training',
  path: '/angebot/personal-training',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angebot/personal-training': typeof AngebotPersonalTrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angebot/personal-training': typeof AngebotPersonalTrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angebot/personal-training': typeof AngebotPersonalTrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/angebot/personal-training'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/angebot/personal-training'
  id: '__root__' | '/' | '/angebot/personal-training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngebotPersonalTrainingRoute: typeof AngebotPersonalTrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebot/personal-training': {
      id: '/angebot/personal-training'
      path: '/angebot/personal-training'
      fullPath: '/angebot/personal-training'
      preLoaderRoute: typeof AngebotPersonalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngebotPersonalTrainingRoute: AngebotPersonalTrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
